spring.application.name=dungeoncrawler2

spring.datasource.url=jdbc:postgresql://localhost:5432/dungeoncrawler
spring.datasource.username=postgres
spring.datasource.password=${SECRET_KEY}

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
